### ISSUE TITLE
Does this work for desktop ionic sites too? 

### ISSUE THREAD

**Issue by suyogdilipkale** [SiddharthaRRamesh/ionic-starter-oauth#10]
Does ionic-starter-oauth works for both web and native app?

I means that does it work if user has installed native ionic application on iOS or Android device and then uses facebook native app to authenticate AS WELL AS user on desktop browser use the desktop version of same ionic application & authenticate using facebook browser application? Is it same code is handling platform specific execution ? 

If not what is the better package to use on both native and desktop browser platform

**Comment by srameshr** [comment]
This is for installed (running inside webview apps). But same code should work on browsers considering you replace the plugins with JS libs which basically do the same thing..
