### ISSUE TITLE
Issue while trying to inject cordova-plugin-googleplus into my controller

### ISSUE THREAD

**Issue by OSSDeveloper** [SiddharthaRRamesh/ionic-starter-oauth#2]
Hi ,

Am trying to use the cordova-plugin-googleplus plugin and, am getting an error. Please check the issue. 
Am pasting the error msg from browser(Am running it in device, using browser just for error log) :-

Error: [$injector:unpr] Unknown provider: $cordovaGooglePlusProvider <- $cordovaGooglePlus <- loginController
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24cordovaGooglePlusProvider%20%3C-%20%24cordovaGooglePlus%20%3C-%20loginController
at REGEX_STRING_REGEXP (ionic.bundle.js:8762)
at ionic.bundle.js:12696
at Object.getService as get
at ionic.bundle.js:12701
at getService (ionic.bundle.js:12843)
at invoke (ionic.bundle.js:12875)
at Object.instantiate (ionic.bundle.js:12892)
at ionic.bundle.js:17161
at IonicModule.controller.self.appendViewElement (ionic.bundle.js:48253)

And, here is my controller :- 
var loginController = starterApp.controller('loginController', function($scope, $cordovaGooglePlus){
$cordovaGooglePlus.login().then(function(data){
alert(data);
}, function(err){
alert(err)
});
});

**Comment by srameshr** [comment]
Use the ng-cordova file here:

https://github.com/SiddharthaRRamesh/ionic-starter-oauth/blob/master/www/lib/ionic/js/ng-cordova.js

**Comment by OSSDeveloper** [comment]
Hi @SiddharthaRRamesh ,

```
Thanks for a fast reply. I tried by using ng-cordova.js from the link you gave. Its giving the error in the pic attached. I previously tried by injecting the 'ngCordova.plugins.googleplus' into 'ngCordova.plugins' module. But, in vain. My mail Id is vijaybhaskar.puranam@gmail.com . Please drop me a mail so that I can send you my complete code. There might be some mistake I am doing with google plus plugin which, you might be able to find out.
```

![screenshot](https://cloud.githubusercontent.com/assets/5099615/7627803/f27f5ac4-fa38-11e4-8dc0-2143065edf01.png)

**Comment by SiddharthaRRamesh** [comment]
siddhartharramesh@gmail.com

Fell free to contact me.

**Comment by srameshr** [comment]
I went through your code. Try calling it as an effect of an event handler or after platform is ready. 

``` javascript
var loginController = starterApp.controller('loginController', function($scope, $cordovaGooglePlus){
    $scope.isAvailable = function(){
        $cordovaGooglePlus.login()
        .then(function(data) {
            alert(data)
        }, function(err) {
            alert(err)
        });
    }
});
```

This only works in your device and not on your desktop browser. You can check that via:

``` javascript
$scope.isAvailable = function(){
  if($window.cordova){
    //call $cordovaGooglePlus
  }
  else{
    //something else
  }
}
```

Remove `onclick` in your view and use `ng-click`
