### ISSUE TITLE
Unable to install plugins with ionic framework app

### ISSUE THREAD

**Issue by DipakMahapurkar** [SiddharthaRRamesh/ionic-starter-oauth#9]
Hello @srameshr,
I am trying to follow your steps but i get this error at installation of plugins

cordova -d plugin add /Users/Desktop/Ionic 2 Demo/phonegap-facebook-plugin --variable APP_ID="App_id" --variable APP_NAME="App_name"

Executing "before_plugin_add"  hook for all plugins.
No version specified, retrieving version from config.xml
No version given in config.xml, attempting to use plugin engine info
Error: Registry returned 404 for GET on https://registry.npmjs.org/ionic-oauth
    at makeError (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
    at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
    at Request._callback (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/node_modules/request/request.js:963:12)

please help me.
Thank You !!

**Comment by srameshr** [comment]
So, did you download the latest version of the cordova facebook plugin and then tried to execute
`cordova plugin add` inside your root of the ionic project?

PS: You should use this facebook plugin: https://github.com/jamielob/cordova-plugin-facebook4

**Comment by DipakMahapurkar** [comment]
Thanks for reply. I also tried ur given link but it will give build time error duplicate of Bolts.Framework,
 I check in my app but there is no duplicate entry of this framework.

**Comment by srameshr** [comment]
I would suggest you to remove the platform first:

```
  cordova platform remove android --save
```

Then run this command in order to uninstall plugins

```
  cordova plugin remove cordova-plugin-facebook4 --save

```

Then try to add the platform again and then follow this up by adding the plugin.

**Comment by DipakMahapurkar** [comment]
Hey @srameshr i am trying it on my iOS app, is there any solution for it?

**Comment by srameshr** [comment]
Just replace `android` with `ios`.

```
  cordova platform remove ios --save 
```

**Comment by DipakMahapurkar** [comment]
I just tried adding and removing iOS platform but it will give an error build failed due to:
duplicate symbol _llvm.cmdline in:
    IdeasApp/Plugins/cordova-plugin-facebook4/Bolts.framework/Bolts(BFAppLinkTarget.o)
    IdeasApp/Plugins/cordova-plugin-facebook4/Bolts.framework/Bolts(BFCancellationTokenRegistration.o)

duplicate symbol _llvm.cmdline in:
    IdeasApp/Plugins/cordova-plugin-facebook4/Bolts.framework/Bolts(BFAppLinkTarget.o)
    IdeasApp/Plugins/cordova-plugin-facebook4/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKSystemAccountStoreAdapter.o)

duplicate symbol _llvm.embedded.module in:
    App/Plugins/cordova-plugin-facebook4/Bolts.framework/Bolts(BFAppLinkTarget.o)
    App/Plugins/cordova-plugin-facebook4/FBSDKShareKit.framework/FBSDKShareKit(FBSDKAppInviteContent.o)
ld: 262 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* BUILD FAILED **

The following build commands failed:
    Ld build/emulator/App.app/App normal i386
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Desktop/Ionic Demo/App/platforms/ios/cordova/build-debug.xcconfig,-project,App.xcodeproj,ARCHS=i386,-target,App,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Desktop/Ionic  Demo/App/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Desktop/Ionic Demo/App/platforms/ios/build/sharedpch

My plugin list:
com.raananw.imageResizer 0.1.2 "ImageResizer"
cordova-plugin-camera 2.1.1 "Camera"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-email-composer 0.8.3 "EmailComposer"
cordova-plugin-facebook4 1.7.0 "Facebook Connect"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-googleplus 4.0.9 "Google+"
cordova-plugin-image-picker 1.0.8 "ImagePicker"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-toast 2.5.0 "Toast"
cordova-sqlite-storage 1.2.0 "Cordova sqlite storage plugin (core version)"
ionic-plugin-keyboard 2.0.1 "Keyboard"
org.pbernasconi.progressindicator 1.1.0 "Progress Indicator"

and my ionic info:

My system information:

Cordova CLI: 6.1.1
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v5.10.1
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by srameshr** [comment]
First uninstall `cordova-plugin-facebook4 1.7.0` then remove the platform

**Comment by DipakMahapurkar** [comment]
no luck, get again same problem

**Comment by srameshr** [comment]
Why dont you delete the project and start with the fresh installation.

**Comment by DipakMahapurkar** [comment]
Thanks for replay, I also tried it but no luck ... did u try it on ios platform with brand new project?  if yes please send me steps or code...if u don't mind ....

**Comment by srameshr** [comment]
```
ionic start your_app blank
```

```
ionic platform add ios
```

This should do it! Make sure you remove the whole project except for your `www` stuff 👍
